- module/net.c
With the Merlin network IO now being completely handled inside the
Naemon event loop, its possible under high numbers of checks and TCP
congestion / full buffers that we could end up poll()'ing and blocking
for 100ms for each check Naemon processes.  This starves the even loop
for resources, Naemon cannot process check results, and we are not
reading from the Merlin sockets.  This then cascades to peers as they
begin to block on a full TCP write buffer.
I've reduced the amount of time poll() will block for from 100ms to
10ms.  I wonder if we should not block at all in the event loop.
> Reduce blocking in main Naemon event loop

- apps/libexec/oconf.py.in
We look for cfg_file=foobar but we write cfg_dir=foobar.  Fix that up.
> Fix config file munging typo

- apps/libexec/oconf.fetch.sh.in
The mon oconf reload command is obsolete now.
However any user with sudo rights can copy config from master to poller
and can restart monitor.
MON-9232
> Monitor not reloaded on poller after "mon oconf fetch"

- apps/libexec/oconf.py.in
We should always restart even though some error occurs.
Otherwise we will not be able to push configuration and restart other nodes in case
some arbitrary files was not pushed due to some error
Signed-off-by: Robin Engström <robin.engstrom@op5.com>
> oconf.py.in: always restart

- module/hooks.c
In commit
8df9f641d8a73d87e955a174253b51703f721bdc
MAGIC_NONET is meant for hdr->code
a conditional was removed from send_generic() that filtered packets
if hdr.selection == MAGIC_NONET.  This is clearly a bug as the
MAGIC_NONET value is meant for hdr.code to identify the packet, not
route it.  However, it has the same value as DEST_BROADCAST.
In most (all?) cases where we do not want to send a packet on the
network and hdr.code is set to MAGIC_NONET hdr.selection is left
unchanged from its initialized value of DEST_BROADCAST.  So, the removed
code was actually the final check for not sending MAGIC_NONET packets on
the network.  Since the above, I've had some really weird behavior with
merlin bouncing checks between nodes.
This patch adds back check for hdr.code == MAGIC_NONET so that …
> module/hooks.c: Do not place MAGIC_NONET packets on the network

- apps/libexec/oconf.py.in
A bug was created when parallelizing oconf push which would cause all nodes
to be restarted when only one was selected. This would all nodes to be
restarted n-1 times where n is the number of nodes in a cluster when pushing config
via merlin.
This is a quick fix which was discovered by Benjamin Ritcey in support ticket:
https://jira.op5.com/browse/SUPPORT-23248
Part of MON-10309
Signed-off-by: Robin Engström <robin.engstrom@op5.com>
> oconf.py.in: only restart wanted nodes

- features/startup.feature
- features/step_definitions/service_startup.rb
- module/module.c
- shared/node.c
- shared/node.h
This commit allows Merlin to function with nodes which DNS cannot be
resolved at startup. If no a given node could not be resolved at
startup merlin will try to resolve the nodes during the connect_to_all
function, which checks if disconnected nodes has become online.
Note that if the DNS changes, for a given node, then Merlin should be
restarted, as it will not attempt to resolve nodes that previously has
been resolved.
> Allow nodes with unresolvable DNS names

- apps/libexec/restart.sh.in
- features/config_sync_passive_poller.feature
- features/step_definitions/service_startup.rb
- shared/node.c
This is the fix for MON-9774, that ensures that a passive poller with a specified mon oconf fetch command correctly fetches updates config from the master.
> Passive poller: Correctly fetch object config.

- features/check_result_output.feature
- tests/cukemerlin/base/json.c
This commit ensures that the JSON library used for the cukemerlin tests
does not insert an extra escape if a newline is already escape in the
input.
This fix is needed for Merlin to pass tests with Naemon 1.0.7, which correctly escapes newlines in the long output of check results.
This fixes MON-11000
> Tests,JSON: do not escape already escaped newlines

- apps/mon.py.in
Earlier boolean output of "mon" command was not recognised in mon.py.in
file. so it was returning exit code .
Added code to check the boolean output of "mon" command.
This fixes issue MON-11302
Co-Authored-By: Jacob Hansen <jhansen@op5.com>
Signed-off-by: devesh thakur <dthakur@op5.com>
> mon.py: correctly handle boolean return values

- COPYING
The license included had some additional "fluff" that we probably do not
want. This project has always been GPLv2 and we might as well stick with
it.
> Use proper GPLv2 license

- data/merlin.in
This fixes MON-11632.
The previous way of checking the version number was failing on both
RHEL as well as EL6 (but here it only gave an error message, since the
logic allowed for it to fail and go to the else clause).
The above method works on both CentOS 6 and RHEL 7.
Signed-off-by: Johan Thorén <jthoren@op5.com>
> Fix logrotate version check for RHEL

- data/merlin.in
This fixes MON-11632.
Instead of trying to figure out what version of EL is running
by grepping text files, this now checks if the systemctl command
exists directly instead.
Signed-off-by: Johan Thoren <jthoren@op5.com>
> Replace version check with command check

- merlin.spec
- sudo/merlin.in
When installing the RPM package, create an user group for monitor
operators to be able to run certain `mon` commands as root.
This fixes MON-11159
> Create group during installation for sudoers use

- sudo/merlin.in
Fix the issue that `mon node` and `mon check` commands only allowed use
with optional parameters, which was not intended. Also allow to run
`sudo mon node/check` to display usage text.
This fixes MON-11159
> Fix sudoers rules for allowed mon commands

- apps/libexec/node.py
Previously the 'mon node status' command would always exit with
exit code 0, regardless of whether there were any inactive
nodes in the listing or not.
This patch adds a new variable that is used to return exit
code 1 in the case where there is one or more inactive
nodes listed.
> Return exit code 1 if there are inactive nodes

- merlin.spec
- op5build/ci_config.yml
Add LMD dependency
As of Monitor 8, livestatus queries are made against LMD. To ensure all
integration tests works correct, we add LMD as a dependency to the
package.
------
Add workaround for EL7.7 bug related to MySQL
A known issue in EL7.7 causes issues with the mysql_install_db script
used during the tests. A workaround is added in the ci_config file.
More info can be found at section 8.7 on:
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/7.7_release_notes/known_issues
> Add lmd dependency and fix build on EL 7.7

- Makefile.am
- apps/libexec/reportdata.py
Adds a new command, which outputs errors if the latest entry in the
report_data table does not match the state when querying livestatus.
> Add script for checking report_data consistency

- module/hooks.c
- op5build/ci_config.yml
Prior to this commit the external command DEL_DOWNTIME_BY_HOST_NAME was
send to all nodes. However we should not send this command to a poller,
if that poller isn't handling the host.
This is part of MON-9109
> Limit DEL_DOWNTIME_BY_HOST_NAME to relevant nodes (7.5)

- module/hooks.c
Prior to this commit the external command DEL_DOWNTIME_BY_HOST_NAME was
sent to all nodes. However we should not send this command to a poller,
if that poller isn't handling the host.
This is part of MON-9109
> Limit DEL_DOWNTIME_BY_HOST_NAME to relevant nodes

- merlin.spec
As we do not want to write to a database with the slim packages of
merlin, we remove the dependencies to libdbi and friends.
Also added op5-monitor-user-slim as a dependency as the monitor user is
referenced.
> Remove DB dependencies for slim packages

- apps/libexec/modules/nagios_command.py
This adds support for the Naemon external command
DEL_DOWNTIME_BY_HOST_NAME using `mon ecmd`.
This is part of: MON-11872
> Add support for DEL_DOWNTIME_BY_HOST_NAME

- README.md
It has been a long time since Merlin has supported storing current
status information in a database, and I am not sure merlin was ever the
backend for Ninja.
This gets rid of that text, to bring the README slightly more in
line with reality.
> Update README removing status information handling

- shared/logging.c
In some very rare cases, very long log message might be passed to the log function. If the resulting log message is longer than 4096, we would segfault when accessing `msg[len]`, because the return value of `vsnprintf` is "he number of characters that would have been written if n had been sufficiently large"
To fix this, we set the len to 4095, in case the the message is too long.
This fixes MON-12041
> Fix segmentation fault on long log messages

- shared/logging.c
In some very rare cases, very long log message might be passed to the log function. If the resulting log message is longer than 4096, we would segfault when accessing `msg[len]`, because the return value of `vsnprintf` is "he number of characters that would have been written if n had been sufficiently large"
To fix this, we set the len to 4095, in case the the message is too long.
This fixes MON-12041
> Fix segmentation fault on long log messages (7.5)

- data/merlin.in
When doing a restart of Naemon and Merlin, we always restart the Merlin
daemon first, follow by restarting Naemon. However the logrotation script
of EL7, does it the opposite way around.
This commit changes the logrotation script to restart in the right
order.
This might fix: MON-11910
> Logrotate: Restart merlind first, then Naemon

- data/merlin.in
When doing a restart of Naemon and Merlin, we always restart the Merlin
daemon first, follow by restarting Naemon. However the logrotation script
of EL7, does it the opposite way around.
This commit changes the logrotation script to restart in the right
order.
This might fix: MON-11910
> Logrotate: Restart merlind first, then Naemon (7.5)

- apps/libexec/restart.sh.in
- apps/libexec/start.sh
- apps/libexec/stop.sh
Since we no longer support EL6, we can migrate to use systemctl without
any issues.
Also added a start command to the op5-monitor service in order to fix
MON-11559.
> Use systemctl instead of service

- apps/libexec/restart.sh.in
- apps/libexec/start.sh
In the current CI system, many components rely on the `mon restart` and
`mon start` commands. However the CI system, just install the required
packages (as defined by the rpm dependencies). This results in the
op5-monitor service being missing in quite a few CI tests, causing the
start/restart scripts to fail.
This commit therefore first checks if the op5-monitor service exists on
the system, before attempting to start it.
> Apps: Conditional start of op5-monitor service

- apps/libexec/check.py
This fixes a regression that occurred due to the fix of MON-10954.
If there are no expired checks, the list of expired checks is empty,
hence the 0th index could not be checked. This commit puts a safeguard
around the check.
This fixes: MON-12097
> Apps: fix exception in mon check distribution

- .gitignore
- Makefile.am
- apps/libexec/.gitignore
- apps/libexec/merlinkey.py.in
- configure.ac
- merlin.spec
- shared/encryption.c
- shared/encryption.h
- shared/ipc.c
- shared/node.c
- shared/node.h
- tests/test-hooks.c
- tools/keygen.c
This commit implements encyrption of Merlin communication on port 15551.
The implementation is done using libsodium and the encryption cipher
used is XSalsa20.
The encryption is done on the body of the merlin packet, the header
remains unencrypted.
With this commit the merlin packet header is increased, to accomendate
sending the nonce in the header. Due to this the
`MERLIN_PROTOCOL_VERSION` is increased.
This fixes MON-12110
> Implement public key encryption

- Makefile.am
- features/step_definitions/service_startup.rb
- op5build/ci_config.yml
- shared/encryption.c
- shared/node.c
- tests/cukemerlin/steps/steps_merlin.c
- tests/merlincat/event_packer.c
- tests/merlincat/merlincat.c
- tests/merlincat/merlincat_encryption.c
- tests/merlincat/merlincat_encryption.h
- Fix a bug in the encryption implementation when sending the same pkt to multiple nodes
- Run test-suite with encrypted merlin, with the exception of a couple of tests (see comment in the `ci_config.yml` for more details).
> Run test-suite with encryption enabled

- apps/libexec/node.py
- shared/ipc.c
With this commit the encryption status is added to the node info dump.
This in turn allows us to print the encryption status when executing `mon
node status`.
This fixes: MON-12111
> Apps: Show encryption status in mon node status

- module/module.c
- shared/encryption.c
- shared/encryption.h
- shared/node.c
- shared/node.h
For performance improvements, we precalculate the shared encryption key
at configuration time. This reduces the performance penalty for enabling
encryption.
This fixes: MON-12187
Signed-off-by: Jacob Hansen <jhansen@itrsgroup.com>
> Pre-calculate shared encryption key

- apps/libexec/merlinkey.py.in
The generated keys should only be readable by the monitor user. No other
users on the system should be able to read the keys.
> Set permission 400 permissions for encryption keys

- merlin.spec
For the apps-slim package, the keygen tool was missing, causing problems
generating keys on the slim poller.
With this commit we correctly include the keygen tool for the slim
poller, too.
> Spec: Install keygen tool for slim packages

- shared/encryption.c
- shared/node.c
There was a left-over debug log message printed on the 'Warn' level when
enabling encryption. There are already good debug level logs in place
for both encryption and decryption, so this can be removed completely.
Also add a debug messages saying encryption/decryption went OK.
> Encryption: Remove left-over debugging message

- apps/libexec/merlinkey.py.in
On the slim poller we do not have the apache group. Further there is no
reason for the group to be set as apache instead of root as:
- Apache has no need to access the encryption keys
- The group has no access to the file anyway due to the 700 permissions
> Set encryption keys to be owned by root group

- apps/libexec/syscheck/license.sh
This command was previously severely outdated as we no longer use XML
licenses, leading to customer complaints that we are shipping a
defective command. There's probably more things we can do here, and 14
days is arbitrary, but since the plugin this depends on *needs* either
days left or amount of hosts to work, the choice here was either to
check if days left was <0 or <N. I elected to choose an arbitrary number
instead because I can't figure out a valid use case for when you would
want a license with less than 14 days to still be marked as OK. If this
doesn't make sense, we can change it later, but at least "mon sysconf
check license" now works.
> Use check_op5_license instead to validate

- merlin.spec
The log level was always overwritten on package updates. This makes it
hard to choose the your preffered loglevel. With this patch, we no
longer force the `info` log level.
> Don't overwrite log level in merlin.conf

- apps/libexec/syscheck/license.sh
This command was previously severely outdated as we no longer use XML
licenses, leading to customer complaints that we are shipping a
defective command. There's probably more things we can do here, and 14
days is arbitrary, but since the plugin this depends on *needs* either
days left or amount of hosts to work, the choice here was either to
check if days left was <0 or <N. I elected to choose an arbitrary number
instead because I can't figure out a valid use case for when you would
want a license with less than 14 days to still be marked as OK. If this
doesn't make sense, we can change it later, but at least "mon sysconf
check license" now works.
This fixes: MON-12409
> (7.5) Use check_op5_license instead to validate

- module/net.c
If no node where found, we would still call `nm_bufferqueue_destroy`. This
would cause a segmentation fault, as we are trying to access an element
of a `NULL` structure.
Instead we do it after the null pointer check.
Also ensure we free the bufferqueue created in `net_accept_one` if we
don't find a matching node.
> UUID: Don't free bufferqueue if no node were found

- apps/libexec/modules/merlin_conf.py
With this commit `publickey` is added to the list of options which
can be set when adding a new node, this will enable a user to set up
a new encrypted node without having to edit the merlin configuration
file directly.
Signed-off-by: Erik Sjöström <esjostrom@op5.com>
> Enable setting publickey when adding a new node

- apps/libexec/merlinkey.py.in
The monitor user does not have permission to change the group ownership
of the encryption keys to root, so instead we leave the group ownership
unchanged.
Signed-off-by: Erik Sjöström <esjostrom@op5.com>
> Do not set group when chowning encryption keys

- Makefile.am
- apps/libexec/qh.py
- features/runcmd.feature
- features/step_definitions/service_startup.rb
- features/support/merlin_packet_defaults.rb
- merlin.spec
- module/module.c
- module/queries.c
- module/queries.h
- module/runcmd.c
- module/runcmd.h
- shared/codec.c
- shared/node.h
- test_protocol/merlinpkt.py
- tests/cukemerlin/steps/steps_merlin.c
- tests/merlincat/event_packer.c
- tests/merlincat/generate-nebev2kvvec.py
- tests/merlincat/merlincat_codec.c
With this commit we implement a SSH-less `test this check`. A new merlin
QH type is added as well as a new merlin pkt, `RUNCMD_PACKET`.
Using the new QH type, we can send a request to a remote node to execute
a query via the 'testthis' query handler, and the remote node should
respond with the result.
This is part of: MON-12394
> SSH-less test-this-check

- features/connection.feature
- features/notification_persistence.feature
- merlin.spec
- op5build/ci_config.yml
The disabling of tests should probably be temporary. It seems like the failures happen only when running the test-suite in encrypted mode right after running it in non-encrypted. Perhaps they should run on different machines, if that is possible somehow.
At least this seems to work for now.
> Test failures

- shared/cfgfile.c
Messages printed to stdout/err from the Merlin module, is not detected
by the system journal on CentOS. As a result, we would have issues where
Naemon failed to start, due to a error with the merlin config, but the
log messages explaining why is no where to be seen. The previous
workaround would be to start Naemon manually instead of via systemd to
see the errors.
To fix this we use Naemons logging functionality instead, which means we
correctly get the merlin errors printed to stdout/err and they are
correctly logged to the system journal, for troubleshooting.
This also works in the daemon, as `nm_log` just prints to stdout/err in
case there are no Naemon log file.
This fixes: MON-9151
> Log config errors with Naemons log function

- apps/libexec/oconf.py.in
- features/cluster_update.feature
- features/step_definitions/service_startup.rb
- features/support/merlin_packet_defaults.rb
- module/module.c
- module/module.h
- module/script-helpers.c
- module/script-helpers.h
- shared/node.c
- shared/node.h
- shared/shared.c
- tests/merlincat/event_packer.c
With this commit, we add support for a merlin node to run a specific
script, in case a remote node signals that the cluster configuration is
invalid.
To do so, we have a new CTRL command, `INVALID_CLUSTER` which will be
sent when a node connects with incompatible cluster configuration. It
will be sent next time a CTRL_ACTIVE was supposed to be sent. The reason
for this is that we immediately disconnect from a node, when an
incompatible config is seen (i.e before we can manage to send a pkt). However
next time a connection attempt is made, the `CTRL_INVALUD_CLUSTER` packet will
be sent instead of a `CTRL_ACTIVE` pkt as normal.
> Slim poller: Support auto updating

- apps/libexec/node.py
Show the "Last alive: unknown" when a node has not yet been alive
instead of something like this:
"Uptime: unknown. Connected: unknown. Last alive: 2655w 6d 15h 47m 29s
ago"
> Fix mon node status last alive output

- apps/libexec/oconf.py.in
- features/config_sync_passive_poller.feature
- features/support/merlin_packet_defaults.rb
- module/module.c
- module/queries.c
- module/script-helpers.c
- module/script-helpers.h
- shared/node.h
- shared/shared.c
- tests/merlincat/event_packer.c
This commit implements a new feature, that allows one to tell a remote
node to do a `mon oconf fetch`. For example this is useful if you have a
passive poller and you want it to fetch files from the master (for
example updated custom plugins).
It is achieved by:
- Adding a new control packet: CTRL_FETCH
- Calling the fetch command once above ctrl pkt is recieved
- Adding a query handler that allows one to send a CTRL_FETCH packet
- A utility function on the mon oconf script that calls the qh
This fixes: MON-12424
> Implement `mon oconf remote-fetch`

- apps/libexec/oconf.py.in
- module/queries.c
remote-fetch would always print out unknown type, even if everything was
OK, and we would print the output twice from the `mon` tools.
Both of the above has been fixed with this commit.
> Fix remote-fetch output

- merlin.spec
For Slim Poller 2.0 we need the monitor user to be able to write new
files the the monitor directory. This is needed to be able to add public
keys to the default directory.
> Set monitor as owner of merlin conf directory

- apps/libexec/modules/merlin_conf.py
- module/module.c
- module/module.h
- module/script-helpers.c
- module/script-helpers.h
- shared/node.c
- shared/node.h
- shared/shared.c
- shared/shared.h
With this commit we can automatically set merlin nodes to be deleted, in
case they have been inactive for more than a specified amount of time.
This is useful for the Slim Poller/auto-registering use-case to handle
failure modes where the poller doesn't cleans up itself (for example if
being evicted).
> Support automatic deletion of inactive nodes

- apps/libexec/modules/merlin_conf.py
With this commit we add `notifies` to be a valid attribute to set during
`mon node add ...`.
This fixes: MON-12566
> Apps: Add `notifies` as a valid node attribute

- features/connection.feature
- tests/merlincat/event_packer.c
This commit adds a couple of fairly basic UUID tests. We test that a
connection is sucessfull with a correct UUID and doesn't work with an
incorrect UUID.
This fixes: MON-12464
> UUID: Add tests

- README.md
- module/oconfsplit.c
- tests/test-hooks.c
Naemon 1.2.4 changed the function calls to destroy service and
servicegroup objects. This commit changes Merlin oconfsplit code to use
the updated function prototype.
This fixes: MON-12649
> Add support for Naemon 1.2.4

- merlin.spec
Adding apache as the group (rather than root) for the merlin conf dir,
allows the HTTP-API tests to pass.
> Add apache as group of merlin conf dir

- features/step_definitions/database.rb
- merlin.spec
- op5build/ci_config.yml
* Change the deprecated --log argument to --general-log
* Install development tools needed for building ruby gems
* Change to nosetests-2 since we're explicitly using the python2 version
* Bump cucumber version
Fixes: MON-12609
Signed-off-by: Erik Sjöström <esjostrom@itrsgroup.com>
> Changes required for running tests on EL8

- module/module.c
When a node is first initialized, it's `last_action` is set to -1. For our
auto delete logic, we don't use the node's `last_action` in case we've
never seen the node. However we would only check if `last_action` was
zero, and hence we could get a situation where nodes were deleted
automatically right away. This as we would end up calculating the
`last_seen_delta` as `current_time - (-1)`.
> MON-12790: Check negative values of last_action for auto_del

- apps/libexec/modules/merlin_db.py
- merlin.spec
In a previous commit we changed our dependency on MySQLdb to a *build
dependency* on PyMySQL for EL8. With this commit we upgrade PyMySQL to a
strict requirement on EL8, so that we can use it in the merlin_db.py
script.
This is part of MON-12644.
Signed-off-by: Petter Nyström <pnystrom@itrsgroup.com>
> Require PyMySQL on EL8

- merlin.spec
Define unixcat as a dependency, since it's required for the
"mon query ls" command.
> Add unixcat as dependency to merlin-apps

- module/module.c
- shared/node.c
With this commit we add a few exceptions to the auto delete
functionality. This is to ensure that a master doesn't end up taking
over checks that should've been done on a slim poller cluster. This is
done by ensuring we:
- Don't delete nodes when there's a full network outage, i.e if we
haven't heard from any pollers in the group for a while, we don't delete
any nodes in that pollergroup.
- Don't ever auto delete a single remaining node in a poller group
-------
We don't actively test auto_delete for peers/masters, so disable it
entirely to ensure we don't get unwanted effects.
> auto_delete: protect against master takeover

- Makefile.am
- features/active_checks.feature
- features/step_definitions/service_startup.rb
- features/support/merlin_node_config.rb
- module/hooks.c
- module/module.c
- shared/ipc.c
- shared/node.c
- shared/node.h
- shared/pgroup.c
- shared/pgroup.h
With this commit a new merlin option, ipc_blocked_hostgroups, is
introduced. This setting expects a comma seperated list of hostgroups.
Any host or service checks defined in this list will be blocked from
execution on the local node.
No re-assignment of the check is done - meaning the check is only done
if merlin would otherwise schedule the check on another node. This
likely will lead to a significant amount of expired checks, similar to
what would happen if a poller with `takeover=no` is down.
The setting is intended as a safety-net if for some reason your (slim)
pollers are de-registered, and that masters are not supposed/able to
execute checks for specific hostgroups.
This fixes: MON-12802
> Implement ipc_blocked_hostgroups

- apps/libexec/slim-poller.py.in
While removing the actual lock file from the file system looks better,
there is no way to remove it without race conditions. This commit
changes the behaviour to leave the file in place on the file system.
> slim-poller: Don't remove lock file

- configure.ac
With this commit we set the correct Naemon version requirement in the
build files. This should ensure we get a more understandable error
message if attempting to compile against older Naemon versions.
> Correctly set Naemon version requirement

- merlin.spec
It is best practice not to show output of various commands executed in
i.e post steps of an RPM file. With this commit we ensure output from
the `mon log` commands are hidden. Sometimes this would generate quite a
large output cluttering the update log significantly.
Fixes: MON-12848
----
Previously the first thing we did in the post install step, was to stop
the service. However at this point we installed a new systemd service
file on the system, causing systemctl to warn about the updated file. To
ensure we don't get this warning, we move the `daemon-reload` call up to
before we stop the service
> Don't log output to stdout/err during package installation

- apps/libexec/merlinkey.py.in
When using `mon merlinkey generate --write` the configuration setting
was adding without a newline. This caused future lines to be added at
the end of the same line, instead of on a newline. This in turn created
a corrupt merlin configuration.
> Apps: merlinkey add newline when using --write

- apps/reportdata-import.cron
- apps/reportdata-push.cron
- merlin.spec
Remove these cron jobs as they are not in use, and the 'mon log'
functionality they refer to is deprecated as well.
Part of MON-12877.
> Remove sample cron job configs

- features/active_checks.feature
- shared/ipc.c
The logic for tokenizing `ipc_blocked_hostgroups` where broken due to
adding the full input value, rather than the token to the objectlist.
This caused the `ipc_blocked_hostgroups` functionality to be broken when
specifying multiple hostgroups.
Add an additional testcase where we have multiple hostgroups defiend.
> Correctly tokenize ipc_blocked_hostgroups

- op5build/merlin.spec
For merlin-apps package, add a requirement on python2-livestatus, which
provides the Livestatus python API for python 2.
Previously it was distributed as part of the main monitor-livestatus
package, but it's now separated to it's own package.
Part of MON-12934.
> op5build: add dependency on livestatus python lib

- docs/clustering.rst
Correctly specify the IP when adding master01.
> Correct typo in clustering documentation

- CHANGELOG.md
- apps/cluster_tools/cluster_tools.py.in
- docs/merlin.conf.sample
- features/runcmd.feature
- module/queries.c
- module/runcmd.c
- op5build/ci_config.yml
- shared/node.c
- shared/node.h
With this commit we introduce a new node setting called accept_runcmd.
This setting must be enabled on the nodes from which we want to accept
runcmds, in addition to having encryption enabled. This enables us to
set up encrypted nodes without per default also accepting runcmds from
those nodes. This commit also introduces safety checks in order to make
sure we're not accepting or sending runcmds from pollers.
Fixes: MON-13148
Signed-off-by: Erik Sjöström <esjostrom@itrsgroup.com>
> New node setting "accept_runcmd"

- tools/rename.c
This commit updates rename tool so that the file permissions
of logs are preserved when rename tools updates the logs.
This resolves MON-13180.
Signed-off-by: Jerson Dumalaon <jdumalaon@itrsgroup.com>
> Preserve file permissions

- tools/logutils.h
- tools/showlog.c
This commit adds a new command line option --all-nodes to the
showlog tool. This new option will gather logs from all nodes
and create a consolidated list of event logs. Each log is
appended with the node name where the log originated.
This is part of MON-13186
Signed-off-by: Jerson Dumalaon <jdumalaon@itrsgroup.com>
> Add --all-nodes option to showlog

- op5build/ci_config.yml
* Sudo permissions have been moved to op5-monitor-user, so remove the manual config of sudo permissions.
* Remove EL <8 stuff, as the master branch doesn't support older OS anymore.
Part of MON-11764.
> Cleanup old stuff from ci_config post steps

- tests/test-hooks.c
This commit fixes order of test deinitialization based on the reverse order that the resurces were allocated in test initilization. Based on valgrind tests, the nebmodule_deinit was reading from invalid memory area. Fixing this removed the invalid reads.
This resolves MON-13318.
> Fix order of deinit

- op5build/ci_config.yml
This commit installs mysql2 first to avoid version compatibility issue.
Signed-off-by: Eunice Remoquillo <eremoquillo@itrsgroup.com>
> install mysql2 first before other requirements

- op5build/ci_config.yml
This commit pins sequel gem to 5.71.0 due to errors encoutered using the latest version.
This fixes MON-13347.
> Pin Sequel Gem

- tests/test-showlog.c
- tools/showlog.c
This commit uses the provided --first, --last and --limit parameter values
from the command line to extract logs from all nodes based on a limit
instead of extracting all logs. This will reduce the disk space usage
since Ninja will display 7 days by default.
This is part of MON-13363.
Signed-off-by: Jerson Dumalaon <jdumalaon@itrsgroup.com>
> Limit logs from nodes when all-nodes parameter is used

- op5build/ci_config.yml
Ths commit upgrades ruby to 2.7 to fix issues in gem installation of parallel_tests.
This resolves MON-13444.
> Upgrade to ruby 2.7

- apps/libexec/modules/merlin_qh.py
- apps/libexec/tests/test_merlin_qh.py
This commit update the 'mon check distribution' command to remove the deprecated python2 cmp() function for python3 comparison operators. It also adjusts comparison for 'service description' fields to be similar to comparison used in the 'responsible' fields.
Unit testing was also added for affected python function.
This resolves MON-13481.
> Remove deprecated cmp() in merlin apps

- op5build/ci_config.yml
Pinned multi_json version to ensure compatibility 
with ruby version 2.7. Multi_json is needed by rspec 
that is used in cucumber test scripts.
This is part of MON-13581
Signed-off-by: Eunice Remoquillo <eremoquillo@itrsgroup.com>
> Pinned multi_json version for el7
